# https://docs.travis-ci.com/user/trusty-ci-environment/#Using-Trusty
sudo: false
dist: trusty

language: node_js

# https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache: yarn

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: latest

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

matrix:
  include:
    - node_js: 6
      env: BROWSERS=travis_chrome,Firefox
    - node_js: 6
      env: BROWSERS=sl_safari,sl_ie
      addons:
        sauce_connect: true
    - node_js: 6
      env: BROWSERS=sl_edge
      addons:
        sauce_connect: true

script:
  - yarn test -- --browsers $BROWSERS

after_success:
  - if [[ -d coverage/ ]]; then cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js ; fi
