/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
var SUGAR = SUGAR || {};
SUGAR.restDemoData = [
    {
        "route":/\/Cases\/1234/,
        "status":200,
        "httpMethod":"GET",
        "data":{"id":"1234",
            "name":"Hans Dieter P",
            "date_entered":"2012-02-08 19:18:25",
            "date_modified":"2012-02-08 19:18:25",
            "modified_user_id":"ggl-e922f452833a90cd114305590e085bfb",
            "modified_by_name":"Deepali Mittal Szczesny",
            "created_by":"ggl-e922f452833a90cd114305590e085bfb",
            "created_by_name":"Deepali Mittal Szczesny",
            "description":"",
            "deleted":"0",
            "created_by_link":"",
            "modified_user_link":"",
            "assigned_user_id":"ggl-e922f452833a90cd114305590e085bfb",
            "assigned_user_name":"Deepali Mittal Szczesny",
            "assigned_user_link":"",
            "team_id":"1",
            "team_set_id":"1",
            "team_count":"1",
            "team_name":"Global",
            "team_link":"",
            "team_count_link":"",
            "teams":"",
            "salutation":"",
            "first_name":"Hans",
            "last_name":"Dieter P",
            "full_name":"Hans Dieter P",
            "title":"CFO",
            "department":"",
            "do_not_call":"0",
            "phone_home":"",
            "email":"",
            "phone_mobile":"+49 5361 90",
            "phone_work":"+49 5361 90",
            "phone_other":"",
            "phone_fax":"",
            "email1":"hdp@example.com",
            "email2":"",
            "invalid_email":"0",
            "email_opt_out":"0",
            "primary_address_street":"Berliner Ring 2",
            "primary_address_street_2":"",
            "primary_address_street_3":"",
            "primary_address_city":"Wolfsburg",
            "primary_address_state":"",
            "primary_address_postalcode":"38436",
            "primary_address_country":"Germany",
            "alt_address_street":"",
            "alt_address_street_2":"",
            "alt_address_street_3":"",
            "alt_address_city":"",
            "alt_address_state":"",
            "alt_address_postalcode":"",
            "alt_address_country":"",
            "assistant":"",
            "assistant_phone":"",
            "email_addresses_primary":"",
            "email_addresses":"",
            "email":
             [
           	{
           		"email":"jon@smith.com",
           		"is_primary":true,
           		"is_invalid":false,
           		"opted_out":false
           	},
           	{
           		"email":"bob@bob.com",
           		"is_primary":false,
           		"is_invalid":false,
           		"opted_out":true
           	}
             ],
            "picture":"http:\/\/www.austriantimes.at\/thumbnails\/s\/saczuk28_large.jpg",
            "linkedin":"",
            "twitter":"",
            "email_and_name1":"Hans Dieter P &lt;&gt;",
            "lead_source":"",
            "account_name":"",
            "account_id":"",
            "opportunity_role_fields":"",
            "opportunity_role_id":"",
            "opportunity_role":"",
            "reports_to_id":"",
            "report_to_name":"",
            "birthdate":"",
            "portal_name":"",
            "portal_active":"0",
            "portal_password":"",
            "portal_password1":"",
            "portal_app":"",
            "accounts":"",
            "reports_to_link":"",
            "opportunities":"",
            "bugs":"",
            "calls":"",
            "cases":"",
            "direct_reports":"",
            "emails":"",
            "documents":"",
            "leads":"",
            "products":"",
            "contracts":"",
            "meetings":"",
            "notes":"",
            "project":"",
            "project_resource":"",
            "quotes":"",
            "billing_quotes":"",
            "tasks":"",
            "tasks_parent":"",
            "user_sync":"",
            "campaign_id":"",
            "campaign_name":"",
            "campaigns":"",
            "campaign_contacts":"",
            "c_accept_status_fields":"",
            "m_accept_status_fields":"",
            "accept_status_id":"",
            "accept_status_name":"",
            "prospect_lists":"",
            "sync_contact":"",
            "modified_user_name":"Deepali Mittal Szczesny"}
    },
    {
            "route":/\/Contacts\/12345/,
            "status":200,
            "httpMethod":"GET",
            "data":{"id":"12345", "name":"John Aden", "date_entered":"2012-01-30 18:17:04", "date_modified":"2012-01-30 18:17:04", "modified_user_id":"", "modified_by_name":"", "created_by":"", "created_by_name":"", "description":"", "deleted":"0", "created_by_link":"", "modified_user_link":"", "assigned_user_id":"ggl-acf78da02a9a7ab749e989be48e12558", "assigned_user_name":"David Tam", "assigned_user_link":"", "team_id":"1", "team_set_id":"1", "team_count":"1", "team_name":"Global", "team_link":"", "team_count_link":"", "teams":"", "salutation":"", "first_name":"John", "last_name":"Aden", "full_name":"John Aden", "title":"Executive Vice President, General Merchandise", "department":"", "do_not_call":"0", "phone_home":"", "email":"", "phone_mobile":"1-800-925-6278", "phone_work":"+49 5361 90", "phone_other":"", "phone_fax":"", "email1":"jaden@example.com", "email2":"", "invalid_email":"0", "email_opt_out":"0", "primary_address_street":"702 S.W. Eighth St.", "primary_address_street_2":"", "primary_address_street_3":"", "primary_address_city":"Bentonville", "primary_address_state":"Arkansas", "primary_address_postalcode":"72716", "primary_address_country":"USA", "alt_address_street":"", "alt_address_street_2":"", "alt_address_street_3":"", "alt_address_city":"", "alt_address_state":"", "alt_address_postalcode":"", "alt_address_country":"", "assistant":"", "assistant_phone":"", "email_addresses_primary":"", "email_addresses":"", "picture":"", "linkedin":"", "twitter":"", "email_and_name1":"John Aden &lt;&gt;", "lead_source":"", "account_name":"                                                                                                                                                                                                                                                              ", "account_id":"                                    ", "opportunity_role_fields":"                                                                                                                                                                                                                                                              ", "opportunity_role_id":"", "opportunity_role":"", "reports_to_id":"", "report_to_name":"", "birthdate":"", "portal_name":"", "portal_active":"0", "portal_password":"", "portal_password1":"", "portal_app":"", "accounts":"", "reports_to_link":"", "opportunities":"", "bugs":"", "calls":"", "cases":"", "direct_reports":"", "emails":"", "documents":"", "leads":"", "products":"", "contracts":"", "meetings":"", "notes":"", "project":"", "project_resource":"", "quotes":"", "billing_quotes":"", "tasks":"", "tasks_parent":"", "user_sync":"", "campaign_id":"", "campaign_name":"", "campaigns":"", "campaign_contacts":"", "c_accept_status_fields":"                                                                                                                                                                                                                                                              ", "m_accept_status_fields":"                                                                                                                                                                                                                                                              ", "accept_status_id":"", "accept_status_name":"", "prospect_lists":"", "sync_contact":"", "modified_user_name":""}
    },
    {
            "route":/\/Contacts\/123456/,
            "status":200,
            "httpMetod":"GET",
            "data":{"id":"123456", "name":"Larry Page", "date_entered":"2012-01-30 18:17:04", "date_modified":"2012-01-30 18:17:04", "modified_user_id":"", "modified_by_name":"", "created_by":"", "created_by_name":"", "description":"", "deleted":"0", "created_by_link":"", "modified_user_link":"", "assigned_user_id":"ggl-acf78da02a9a7ab749e989be48e12558", "assigned_user_name":"David Tam", "assigned_user_link":"", "team_id":"1", "team_set_id":"1", "team_count":"1", "team_name":"Global", "team_link":"", "team_count_link":"", "teams":"", "salutation":"", "first_name":"Larry", "last_name":"Page", "full_name":"Larry Page", "title":"CEO", "department":"", "do_not_call":"0", "phone_home":"", "email":"", "phone_mobile":"1-650-253-0000", "phone_work":"+49 5361 90", "phone_other":"", "phone_fax":"", "email1":"lpage@example.com", "email2":"", "invalid_email":"0", "email_opt_out":"0", "primary_address_street":"1600 Amphitheatre Parkway", "primary_address_street_2":"", "primary_address_street_3":"", "primary_address_city":"Mountain View", "primary_address_state":"CA", "primary_address_postalcode":"94043", "primary_address_country":"USA", "alt_address_street":"", "alt_address_street_2":"", "alt_address_street_3":"", "alt_address_city":"", "alt_address_state":"", "alt_address_postalcode":"", "alt_address_country":"", "assistant":"", "assistant_phone":"", "email_addresses_primary":"", "email_addresses":"", "picture":"http:\/\/lh5.ggpht.com\/_7ZYqYi4xigk\/SaXJcOm_aLI\/AAAAAAAAEdY\/uR-9UDfKqKU\/s288\/larry_page.jpg", "linkedin":"tlytle", "twitter":"", "email_and_name1":"Larry Page &lt;&gt;", "lead_source":"", "account_name":"                                                                                                                                                                                                                                                              ", "account_id":"                                    ", "opportunity_role_fields":"                                                                                                                                                                                                                                                              ", "opportunity_role_id":"", "opportunity_role":"", "reports_to_id":"", "report_to_name":"", "birthdate":"", "portal_name":"", "portal_active":"0", "portal_password":"", "portal_password1":"", "portal_app":"", "accounts":"", "reports_to_link":"", "opportunities":"", "bugs":"", "calls":"", "cases":"", "direct_reports":"", "emails":"", "documents":"", "leads":"", "products":"", "contracts":"", "meetings":"", "notes":"", "project":"", "project_resource":"", "quotes":"", "billing_quotes":"", "tasks":"", "tasks_parent":"", "user_sync":"", "campaign_id":"", "campaign_name":"", "campaigns":"", "campaign_contacts":"", "c_accept_status_fields":"                                                                                                                                                                                                                                                              ", "m_accept_status_fields":"                                                                                                                                                                                                                                                              ", "accept_status_id":"", "accept_status_name":"", "prospect_lists":"", "sync_contact":"", "modified_user_name":""}
    }
];